### ISSUE TITLE
Add projects to the generated doc

### ISSUE THREAD

**Issue by jreimone** [royk/playwright-feature-reporter#1]
Coincidentally stumbled over this reporter. Looks interesting. I gave it a try and noticed that it could add value to the consumer of the generated doc if one could see the projects in it, too. If you have multiple projects, e.g. for different browsers, the generated doc just contains the same reported features without indication which project it belongs to. Could be grouped by the feature or by the project.

What do you think?

**Comment by royk** [comment]
Thanks! This project is in a very early phase so I'm definitely interested in hearing how others would like to use it. I think this is a good idea, I will work on it. If you have an example repo that shows the problem that could help but I think I understand the issue

**Comment by royk** [comment]
Fixed in 2.3.0
By default projects will not appear (and their features will not be duplicated).
If you want projects to be reported separately, there is now an option `reportProjects` to support that.

**Comment by jreimone** [comment]
@royk I tried it out but I don't see projects in my report. This is how I configured it:

```
{
   reporter: [
      ['playwright-feature-reporter', { outputFile: './REPORT.md', fullReportLink: 'playwright-report/index.html', reportProjects: true }]
   ]
}
```

I use `"playwright-feature-reporter": "^2.3.0"`.

**Comment by jreimone** [comment]
@royk, not fixed as described in my last comment

**Comment by royk** [comment]
Hey, sorry! I'll check it out soon.
